development:
  adapter: postgresql
  encoding: unicode
  database: pr_hero_development
  pool: 5
  username: kate.beavis
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pr_hero_test
  pool: 5
  username: kate.beavis
  password:
